### ISSUE TITLE
build fails on node 6.2.2

### ISSUE THREAD

**Issue by kilianc** [remko/node-itunes-db#1]
```
> itunes-db@0.4.0 install /app/node_modules/itunes-db
> node-gyp rebuild

/bin/sh: 1: xml2-config: not found
gyp: Call to 'xml2-config --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.14-moby
gyp ERR! command "/node/bin/node" "/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/itunes-db
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
```

**Comment by remko** [comment]
It seems like you haven't got libxml2 installed (or that your environment can't find it). `xml2-config` should be in your path.
